---

project_name: logstash-exporter

builds:
  - main: logstash_exporter.go
    binary: logstash-exporter
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - license: MIT
    maintainer: Dmitry Andreev <dmitry.andreev@insales.ru>
    vendor: InSales Rus LLC
    description: Prometheus exporter for the metrics available in Logstash
    formats:
      - deb
